// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	domain "game-server/internal/core/domain"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// LayerRepository is an autogenerated mock type for the LayerRepository type
type LayerRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: layer_id
func (_m *LayerRepository) Get(layer_id string) (domain.Layer, error) {
	ret := _m.Called(layer_id)

	var r0 domain.Layer
	if rf, ok := ret.Get(0).(func(string) domain.Layer); ok {
		r0 = rf(layer_id)
	} else {
		r0 = ret.Get(0).(domain.Layer)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(layer_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLayerRepository creates a new instance of LayerRepository. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewLayerRepository(t testing.TB) *LayerRepository {
	mock := &LayerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
