// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	domain "game-server/internal/core/domain"

	mock "github.com/stretchr/testify/mock"

	ports "game-server/internal/core/ports/repository"

	testing "testing"
)

// PinRepository is an autogenerated mock type for the PinRepository type
type PinRepository struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *PinRepository) Add(_a0 domain.Pin) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Pin) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: pin_id
func (_m *PinRepository) Delete(pin_id string) error {
	ret := _m.Called(pin_id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(pin_id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: filter
func (_m *PinRepository) Find(filter ports.PinFilter) ([]*domain.Pin, error) {
	ret := _m.Called(filter)

	var r0 []*domain.Pin
	if rf, ok := ret.Get(0).(func(ports.PinFilter) []*domain.Pin); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Pin)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(ports.PinFilter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: pin_id
func (_m *PinRepository) Get(pin_id string) (domain.Pin, error) {
	ret := _m.Called(pin_id)

	var r0 domain.Pin
	if rf, ok := ret.Get(0).(func(string) domain.Pin); ok {
		r0 = rf(pin_id)
	} else {
		r0 = ret.Get(0).(domain.Pin)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pin_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *PinRepository) Update(_a0 domain.Pin) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Pin) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPinRepository creates a new instance of PinRepository. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewPinRepository(t testing.TB) *PinRepository {
	mock := &PinRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
